name: verilator-test
on:
  push:
    branches:
      - '5-stages-pipeline'
      - 'main'

jobs:
  ubuntu-18-functional-test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout -dev repository
        uses: actions/checkout@v2.3.4
          with:
            ref: 5-stages-pipeline
      - name: Install prerequisites
        run: |
          sudo apt install -y gtkwave make clang-10 libc++-10-dev libc++abi-10-dev libz-dev
          wget -O verilator4.deb https://github.com/sifive/verilator/releases/download/4.036-0sifive2/verilator_4.036-0sifive2_amd64.deb
          sudo dpkg -i verilator4.deb
          sudo ln -s /usr/local/share/verilator /usr/share/
      - name: Run NSCSCC functional tests
        run: |
          git branch && git checkout 5-stages-pipeline && make vsim -j USE_CLANG=1 VSIM_OPT=1 VSIM_ARGS='--no-status'